force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Clickup_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Clickup_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Clickup External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Clickup_Space__c.field-meta.xml
<CustomField>
    <fullName>Clickup_Space__c</fullName>
    <label>Clickup Space</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Projects</fullName>
                <default>true</default>
                <label>Projects</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Proposal Planning</fullName>
                <default>true</default>
                <label>Proposal Planning</label>
            </value>
            <value>
                <fullName>Proposal Submitted</fullName>
            </value>
            <value>
                <fullName>Proposal Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetClickUpProjectJob.cls
global class GetClickUpProjectJob implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts {
  public static final String CRON_EXP = '0 0 0 1 1/1 ? *';
  String query;
  private Id projectId;

  global GetClickUpProjectJob(){}
  
  global GetClickUpProjectJob(Id projectId){
    this.projectId = projectId;
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    this.query = 'SELECT Id, Clickup_External_ID__c, Name, Clickup_Space__c, ' +
                    '(SELECT Id, Clickup_External_Id__c FROM Project_Deliverables__r WHERE Clickup_External_Id__c != null) ' +
                    'FROM Project__c WHERE (Status__c = \'Planning\' OR Status__c = \'In Progress\' OR Status__c = \'Proposal\') AND Clickup_External_ID__c != null';
    if (projectId != null){
      this.query += ' AND Id = \'' + projectId + '\'';
    }
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<Project__c> projectList) {
    GetClickUpProjectJobService.createClickUpSnapshot(projectList);
  }

  global void finish(Database.BatchableContext BC) {}

  global void execute(SchedulableContext sc) {
    Database.executeBatch(this, 1);
  }

  @AuraEnabled
  public static void getOneClickUpProject(Id projectId){
    Database.executeBatch(new GetClickUpProjectJob(projectId), 1);
  }

}