force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Proposal Planning</fullName>
                <default>true</default>
                <label>Proposal Planning</label>
            </value>
            <value>
                <fullName>Proposal Submitted</fullName>
            </value>
            <value>
                <fullName>Proposal Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectNarrativeJob.cls
global class ProjectNarrativeJob implements Database.Batchable<sObject>, Schedulable {
  public static final String CRON_EXP = '0 0 2 1 1/1 ? *';
  private Integer batchSize = 200;
  String query;

  global Database.QueryLocator start(Database.BatchableContext BC) {
    this.query = 'SELECT ' + getQueryFields() + ' FROM Project__c WHERE Status__c != \'Complete\' AND Status__c != \'Cancelled\' AND RecordType.Name = \'Language Ministry Project\'';
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<Project__c> projectList) {
    ProjectNarrativeJobService.createNarratives(projectList);
  }

  global void finish(Database.BatchableContext BC) {}

  global void execute(SchedulableContext sc) {
    Database.executeBatch(this, this.batchSize);
  }

  global static String schedule(String jobName, String cron) {
    jobName = jobName != null ? jobName : 'Project Narrative Job';
    cron = cron != null ? cron : ProjectNarrativeJob.CRON_EXP;
    return System.schedule(jobName, cron, new ProjectNarrativeJob());
  }

  private String getQueryFields() {
    Map<String, Schema.SObjectField> fieldMap = Schema.SObjectType.Project__c.fields.getMap();

    List<String> fields = new List<String>();
    for (Schema.SObjectField sObjField : fieldMap.values()) {
        Schema.DescribeFieldResult dfr = sObjField.getDescribe();
        fields.add(dfr.getName());
    }

    String fieldString = String.join(fields, ',');
    return fieldString;
  }
}