force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Actual_Received__c.field-meta.xml
<CustomField>
    <fullName>Actual_Received__c</fullName>
    <formula>General_Accounting_Unit__r.Amount_Raised__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Number_of_Active_Deliverables__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Active_Deliverables__c</fullName>
    <inlineHelpText>Not Cancelled.</inlineHelpText>
    <label>Number of Active Deliverables</label>
    <summaryFilterItems>
        <field>Project_Deliverable__c.Status__c</field>
        <operation>equals</operation>
        <value>Planning, In Progress, Complete</value>
    </summaryFilterItems>
    <summaryForeignKey>Project_Deliverable__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Number_of_Complete_Deliverables__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Complete_Deliverables__c</fullName>
    <label>Number of Complete Deliverables</label>
    <summaryFilterItems>
        <field>Project_Deliverable__c.Status__c</field>
        <operation>equals</operation>
        <value>Complete</value>
    </summaryFilterItems>
    <summaryForeignKey>Project_Deliverable__c.Project__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Funding_Need__c.field-meta.xml
<CustomField>
    <fullName>Total_Funding_Need__c</fullName>
    <inlineHelpText>Read Only: Total amount comes from the sum of Project Deliverable costs. This should equal Approved Budget.</inlineHelpText>
    <label>Total Funding Need</label>
    <summarizedField>Project_Deliverable__c.Funding_Need__c</summarizedField>
    <summaryFilterItems>
        <field>Project_Deliverable__c.Status__c</field>
        <operation>equals</operation>
        <value>Planning, In Progress, Complete</value>
    </summaryFilterItems>
    <summaryForeignKey>Project_Deliverable__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ProjectKeyIndicatorsCtrl.cls
public without sharing class ProjectKeyIndicatorsCtrl {

  @AuraEnabled
  public static Project__c fetchData(Id recordId) {
    return [SELECT Id, Actual_Received__c, Total_Funding_Need__c, Number_of_Active_Deliverables__c, Number_of_Complete_Deliverables__c, 
      (SELECT Id, Total_Completed_Tasks__c, Total_Tasks__c FROM Clickup_Status_Snapshots__r ORDER BY CreatedDate DESC LIMIT 1)
      FROM Project__c WHERE Id = :recordId LIMIT 1];
  }

}