force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Strategic_Focus__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Focus__c</fullName>
    <label>Strategic Focus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital Innovation</fullName>
            </value>
            <value>
                <fullName>Frontline Church</fullName>
            </value>
            <value>
                <fullName>Gateway Translation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rising Generations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectKeyIndicatorCtrlTest.cls
@isTest
private class ProjectKeyIndicatorCtrlTest {
    
  @isTest
  static void testProjectKeyIndicatorCtrlTest() {

    Project__c proj = new Project__c(
      Name = 'Test Project',
      Strategic_Focus__c = 'Rising Generations'
    );
    insert proj;

    Test.startTest();
      Project__c res = ProjectKeyIndicatorsCtrl.fetchData(proj.Id);
    Test.stopTest();

    System.assertEquals(res.Id, proj.Id, 'The method should return the project given.');
  }
}