force-app/main/default/objects/Future_Gift_Allocation__c/Future_Gift_Allocation__c.object-meta.xml
<CustomObject>
    <label>Future Ask Allocation</label>
    <nameField>
        <displayFormat>FGA-{0000}</displayFormat>
        <label>Future Ask Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Ask Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Future_Gift_Allocation__c/fields/Allocation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Amount__c</fullName>
    <label>Allocation Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Future_Gift_Allocation__c/fields/Bib_Probability_Total__c.field-meta.xml
<CustomField>
    <fullName>Bib_Probability_Total__c</fullName>
    <description>Adding this field to help calculate remaining balance for funds to be raised on a project 2-2-22 jkrizan</description>
    <formula>Future_Gift__r.Probability_m__c *  Allocation_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Probability Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Future_Gift_Allocation__c/fields/Future_Gift__c.field-meta.xml
<CustomField>
    <fullName>Future_Gift__c</fullName>
    <label>Future Ask</label>
    <referenceTo>Future_Gift__c</referenceTo>
    <relationshipLabel>Future Ask Allocations</relationshipLabel>
    <relationshipName>Future_Gift_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Future_Gift_Allocation__c/fields/General_Accounting_Unit__c.field-meta.xml
<CustomField>
    <fullName>General_Accounting_Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>General Accounting Unit</label>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipName>Future_Gift_Allocations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Future_Gift_Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>IF(NOT(ISBLANK(General_Accounting_Unit__r.Project__c )), General_Accounting_Unit__r.Project__r.Name , &apos;GAU not connected to a Project&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is the Project associated with the General Accounting Unit.</inlineHelpText>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Future_Gift_Allocation__c/fields/Tax_Deductible__c.field-meta.xml
<CustomField>
    <fullName>Tax_Deductible__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Tax-Deductible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/General_Accounting_Unit__c.field-meta.xml
<CustomField>
    <fullName>General_Accounting_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Accounting Unit</label>
    <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FutureGiftAllocationTest.cls
@isTest
public class FutureGiftAllocationTest {
    //Created 1 Feb 2022 to handle the updates to the triggerhandler for project remaining balance calculations --jkrizan
    //because this is accessing the project update, we need to make that data visible to validate the trigger hence SellAllData=true is set
    @isTest(SeeAllData=true)
//Create the method
    static void validateFutureAllocation() {
   	
//Create the test data for after insert check        
       //first create record with null project -- this validates the if statement in the class
       Future_Gift_Allocation__c FGAnoproject = new Future_Gift_Allocation__c(Future_Gift__c='a1h3i000000i20FAAQ', Allocation_Amount__c=100.00, General_Accounting_Unit__c='a0e3i000005xjsbAAA');
        insert FGAnoproject;
         System.assertEquals(null, FGAnoproject.Project__c);
 
//insert with project value
        Future_Gift_Allocation__c FGAwproject = new Future_Gift_Allocation__c(Future_Gift__c='a1h3i000000i20FAAQ', Allocation_Amount__c=100.00, General_Accounting_Unit__c='a0e3i000005xjsbAAA');
       //System.debug('Test Entry for Allocation Amount: ' + FGA.Allocation_Amount__c);

       // Insert New Future Gift Allocation Record (FGA)
       insert FGAwproject;
    
       // Retrieve the new FGA
       FGAwproject = [SELECT Name FROM Future_Gift_Allocation__c WHERE Id =:FGAwproject.Id];
       //System.debug('New Name of FGA Record after trigger fired: ' + FGA.Name);

        //get the new calculation to update the project record
        AggregateResult[] agResults = [SELECT SUM(Bib_Probability_Total__c) from Future_Gift_Allocation__c WHERE General_Accounting_Unit__c ='a0e3i000005xjsbAAA' AND (Future_Gift__r.Stage__c = 'Proposed' OR Future_Gift__r.Stage__c ='Solicitation' OR Future_Gift__r.Stage__c ='Commitment Made')];
		Double dbl_total = (Double)agResults[0].get('expr0');  
        
        //based on the record that I am using the adding of 100 should make the value 2500
        System.assertEquals(1100100, dbl_total);
    
  //check the After Update section of the code with the same FGA record we just tested with.  
  //Lets update the Tax Deductible Field to False
 		FGAwproject.Tax_Deductible__c = False;
        update FGAwproject;
		
        Future_Gift_Allocation__c FGAupdate = [SELECT Name, Tax_Deductible__c FROM Future_Gift_Allocation__c WHERE Id =:FGAwproject.Id];
   		System.assert(FGAupdate.Tax_Deductible__c != True);      
  //lets verify that the calculated amount stays the same        
        AggregateResult[] agResults2 = [SELECT SUM(Bib_Probability_Total__c) from Future_Gift_Allocation__c WHERE General_Accounting_Unit__c ='a0e3i000005xjsbAAA' AND (Future_Gift__r.Stage__c = 'Proposed' OR Future_Gift__r.Stage__c ='Solicitation' OR Future_Gift__r.Stage__c ='Commitment Made')];
		Double dbl_total2 = (Double)agResults2[0].get('expr0');  
        System.assertEquals(1100100, dbl_total2);
    }
    }